"""Add booleans propeprty for phonebook

Revision ID: 6a09b753daa5
Revises: 2399a1f9c5f7
Create Date: 2020-05-17 21:47:27.250411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a09b753daa5'
down_revision = '2399a1f9c5f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phones', sa.Column('banned', sa.Boolean(), nullable=True))
    op.add_column('phones', sa.Column('priority', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phones', 'priority')
    op.drop_column('phones', 'banned')
    # ### end Alembic commands ###
