channels:
  logs:
    id: 706833509750407228
    name: full-logs
  main: main
  public: public
  sound: sound
conf:
  aa:
    sec: 0
    value: true
  autotake:
    sec: 0
    value: false
  conf:
    value: false
