version: '3.7'

services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - postgres.env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: